############################################
# Plugin properties

## Your GitHub username (used by some helper tasks)
pluginOwner = promptt

## The name of your plugin (also used as the Gradle root project name)
pluginName = MobCleaner

############################################
# Test Server Properties (optional; only used by the template's dev-server tasks if you add them)

## The version of Minecraft to use for testing (Paper)
paperVersion = 1.21.1

## The Paper build number to use for testing
paperBuild = 11
